import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Use the conventional sidebar id to ensure broad theme compatibility
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
